/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AvonHeader {
        "country": string;
        "locale": string;
    }
    interface AvonTopbar {
        "settings": any;
    }
    interface CategoryNav {
        "categories": any[];
    }
    interface DesktopMenu {
        "data": any;
        "settings": any;
    }
    interface MobileMenu {
        "categoryList": any[];
        "settings": any;
    }
    interface SearchBar {
    }
}
declare global {
    interface HTMLAvonHeaderElement extends Components.AvonHeader, HTMLStencilElement {
    }
    var HTMLAvonHeaderElement: {
        prototype: HTMLAvonHeaderElement;
        new (): HTMLAvonHeaderElement;
    };
    interface HTMLAvonTopbarElement extends Components.AvonTopbar, HTMLStencilElement {
    }
    var HTMLAvonTopbarElement: {
        prototype: HTMLAvonTopbarElement;
        new (): HTMLAvonTopbarElement;
    };
    interface HTMLCategoryNavElement extends Components.CategoryNav, HTMLStencilElement {
    }
    var HTMLCategoryNavElement: {
        prototype: HTMLCategoryNavElement;
        new (): HTMLCategoryNavElement;
    };
    interface HTMLDesktopMenuElement extends Components.DesktopMenu, HTMLStencilElement {
    }
    var HTMLDesktopMenuElement: {
        prototype: HTMLDesktopMenuElement;
        new (): HTMLDesktopMenuElement;
    };
    interface HTMLMobileMenuElement extends Components.MobileMenu, HTMLStencilElement {
    }
    var HTMLMobileMenuElement: {
        prototype: HTMLMobileMenuElement;
        new (): HTMLMobileMenuElement;
    };
    interface HTMLSearchBarElement extends Components.SearchBar, HTMLStencilElement {
    }
    var HTMLSearchBarElement: {
        prototype: HTMLSearchBarElement;
        new (): HTMLSearchBarElement;
    };
    interface HTMLElementTagNameMap {
        "avon-header": HTMLAvonHeaderElement;
        "avon-topbar": HTMLAvonTopbarElement;
        "category-nav": HTMLCategoryNavElement;
        "desktop-menu": HTMLDesktopMenuElement;
        "mobile-menu": HTMLMobileMenuElement;
        "search-bar": HTMLSearchBarElement;
    }
}
declare namespace LocalJSX {
    interface AvonHeader {
        "country"?: string;
        "locale"?: string;
    }
    interface AvonTopbar {
        "settings"?: any;
    }
    interface CategoryNav {
        "categories"?: any[];
    }
    interface DesktopMenu {
        "data"?: any;
        "settings"?: any;
    }
    interface MobileMenu {
        "categoryList"?: any[];
        "settings"?: any;
    }
    interface SearchBar {
    }
    interface IntrinsicElements {
        "avon-header": AvonHeader;
        "avon-topbar": AvonTopbar;
        "category-nav": CategoryNav;
        "desktop-menu": DesktopMenu;
        "mobile-menu": MobileMenu;
        "search-bar": SearchBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "avon-header": LocalJSX.AvonHeader & JSXBase.HTMLAttributes<HTMLAvonHeaderElement>;
            "avon-topbar": LocalJSX.AvonTopbar & JSXBase.HTMLAttributes<HTMLAvonTopbarElement>;
            "category-nav": LocalJSX.CategoryNav & JSXBase.HTMLAttributes<HTMLCategoryNavElement>;
            "desktop-menu": LocalJSX.DesktopMenu & JSXBase.HTMLAttributes<HTMLDesktopMenuElement>;
            "mobile-menu": LocalJSX.MobileMenu & JSXBase.HTMLAttributes<HTMLMobileMenuElement>;
            "search-bar": LocalJSX.SearchBar & JSXBase.HTMLAttributes<HTMLSearchBarElement>;
        }
    }
}
