/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AvonHeader {
    }
    interface AvonTopbar {
    }
    interface CategoryNav {
        "categories": any[];
    }
    interface DesktopMenu {
        "data": any;
    }
}
declare global {
    interface HTMLAvonHeaderElement extends Components.AvonHeader, HTMLStencilElement {
    }
    var HTMLAvonHeaderElement: {
        prototype: HTMLAvonHeaderElement;
        new (): HTMLAvonHeaderElement;
    };
    interface HTMLAvonTopbarElement extends Components.AvonTopbar, HTMLStencilElement {
    }
    var HTMLAvonTopbarElement: {
        prototype: HTMLAvonTopbarElement;
        new (): HTMLAvonTopbarElement;
    };
    interface HTMLCategoryNavElement extends Components.CategoryNav, HTMLStencilElement {
    }
    var HTMLCategoryNavElement: {
        prototype: HTMLCategoryNavElement;
        new (): HTMLCategoryNavElement;
    };
    interface HTMLDesktopMenuElement extends Components.DesktopMenu, HTMLStencilElement {
    }
    var HTMLDesktopMenuElement: {
        prototype: HTMLDesktopMenuElement;
        new (): HTMLDesktopMenuElement;
    };
    interface HTMLElementTagNameMap {
        "avon-header": HTMLAvonHeaderElement;
        "avon-topbar": HTMLAvonTopbarElement;
        "category-nav": HTMLCategoryNavElement;
        "desktop-menu": HTMLDesktopMenuElement;
    }
}
declare namespace LocalJSX {
    interface AvonHeader {
    }
    interface AvonTopbar {
    }
    interface CategoryNav {
        "categories"?: any[];
    }
    interface DesktopMenu {
        "data"?: any;
    }
    interface IntrinsicElements {
        "avon-header": AvonHeader;
        "avon-topbar": AvonTopbar;
        "category-nav": CategoryNav;
        "desktop-menu": DesktopMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "avon-header": LocalJSX.AvonHeader & JSXBase.HTMLAttributes<HTMLAvonHeaderElement>;
            "avon-topbar": LocalJSX.AvonTopbar & JSXBase.HTMLAttributes<HTMLAvonTopbarElement>;
            "category-nav": LocalJSX.CategoryNav & JSXBase.HTMLAttributes<HTMLCategoryNavElement>;
            "desktop-menu": LocalJSX.DesktopMenu & JSXBase.HTMLAttributes<HTMLDesktopMenuElement>;
        }
    }
}
